#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH
nohup java -server -Dtoken=QA0ONQ2P9CC9RZLJZY6W1I95Z7ALC -Dspring.profiles.active=prod -jar $OPENSHIFT_REPO_DIR/build/libs/bh-*.jar &
